<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PC4121" ignored="0" tests="2" failures="1" timestamp="2021-08-12T16:22:42 IST" time="12.462" errors="0">
  <testcase name="hello" time="6.623" classname="TestNG">
    <failure type="java.lang.AssertionError" message="expected [Tools QA - How to Write TestNG Test Case (with examples) | ToolsQA] but found [Tools QA - TestNG Groups | How to run TestNG tests in Groups?]">
      <![CDATA[java.lang.AssertionError: expected [Tools QA - How to Write TestNG Test Case (with examples) | ToolsQA] but found [Tools QA - TestNG Groups | How to run TestNG tests in Groups?]
at TestNG.hello(TestNG.java:33)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- hello -->
  <testcase name="verifyTitle" time="5.769" classname="TestNG"/>
</testsuite>
